version: "3.8"
services:
  grafana:
    image: grafana/grafana:8.0.5
    environment:
      - GF_DEFAULT_APP_MODE=development   
    volumes:
      - ./neo4j-datasource-plugin/dist:/var/lib/grafana/plugins/neo4j-datasource-plugin
    ports:
      - 3000:3000

  neo4j:
    image: neo4j:4.1.10     
    volumes:
      - neo4j-data:/data
    ports:
      - 7474:7474
      - 7687:7687

volumes:
  neo4j-data:      
